name: Update Configs
permissions: write-all

on:
  push:
    branches: [main]
  schedule:
    - cron: "*/60 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: cd Files && pip install -r requirements.txt
      - run: cd Files && python app.py
      - run: cd Files && python sort.py
      - uses: EndBug/add-and-commit@v7
        with:
          author_name: T3stAcc
          message: Updated!
          add: .
          push: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
